cluster:
    name: sim_ex_stream
    time: 10
    directory: {sim_out_dir}streams/
    system: cedar
    nodes: 1
    ompnum: 2
    pernode: 24
    mem: 0
    venv: {venv_dir}
    queue: batch
    account: rpp-chime
    queue_sys: slurm


pipeline:

    logging:
        root: INFO

    tasks:
        - type: draco.core.task.SetMPILogging
          params:
              level_rank0: DEBUG
              level_all: INFO

        - type: draco.core.io.LoadProductManager
          out: manager
          params:
              product_directory: {sim_out_dir}products/

        - type: draco.core.io.LoadMaps
          out: map_21cm
          params:
              maps:
                - files:
                    - "{sim_out_dir}cora_maps/in_map_21cm.h5"

        - type: draco.synthesis.stream.SimulateSidereal
          requires: manager
          in: map_21cm
          out: sstack_21cm
          params:
              save: Yes
              tag: "21cm"
              output_name: "{sim_out_dir}streams/stream_{{tag}}.h5"

        - type: draco.core.io.LoadMaps
          out: map_fg
          params:
              maps:
                - files:
                    - "{sim_out_dir}cora_maps/in_map_fg.h5"

        - type: draco.synthesis.stream.SimulateSidereal
          requires: manager
          in: map_fg
          out: sstack_fg
          params:
              save: Yes
              tag: "fg"
              output_name: "{sim_out_dir}streams/stream_{{tag}}.h5"
